<?php

namespace innobisBundle\Repository;

/**
 * FormsAnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormsAnsRepository extends \Doctrine\ORM\EntityRepository
{
}
