<?php

namespace innobisBundle\Repository;

/**
 * FormsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormsRepository extends \Doctrine\ORM\EntityRepository
{
}
